chore: 修改 vite template
Tencent/tdesign-starter-cli pull request #56
Opened 2024-04-07 14:31 UTC by RSS1102

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [x] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2024-04-07 14:34 UTC, RSS1102 commented
![image](https://github.com/Tencent/tdesign-starter-cli/assets/81673017/9b68ef8a-a470-4caf-9284-80a45f6ffe18)

2024-04-08 10:43 UTC, RSS1102 commented
![image](https://github.com/Tencent/tdesign-starter-cli/assets/81673017/272e7b61-b378-43f3-b158-db0dacc104cd)

2024-04-15 10:48 UTC, uyarn commented on templates/vite/react-lite/public/TDesign-logo_light.svg
换个名字吧.. 太长了

2024-04-15 10:49 UTC, uyarn commented on templates/vite/vue-lite/README.md
> +  <a href="https://github.com/Tencent/tdesign-react-starter/blob/develop/LICENSE">
这些调整链接看一下哦

2024-04-16 13:12 UTC, RSS1102 commented
通过`npm run dev init` 测试
vite-vue2
![image](https://github.com/Tencent/tdesign-starter-cli/assets/81673017/4494c846-b64e-430e-b05b-52a1839c99c8)

vite-vue3
![image](https://github.com/Tencent/tdesign-starter-cli/assets/81673017/162c38d4-5e7a-457f-967d-596d2d55a19b)

vite-react
![image](https://github.com/Tencent/tdesign-starter-cli/assets/81673017/177b2312-4e93-4311-bc45-b6ccadac6282)

2024-04-17 11:57 UTC, uyarn requested changes
文件名好像没改全哦

2024-04-18 02:10 UTC, uyarn approved these changes

2024-04-18 02:10 UTC, merged